apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
  labels:
    app: mediawiki
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: mediawiki

